Numpy is a fundamental library for scientific computing in python. it provides support for arrays and matrics, along with a collection of mathematical functions to operate on these data structure, in this lession we will cover the basic of Numpy, focusing on arrays and vectorized operation.

In [2]:
!pip install numpy


In [2]:
from typing_extensions import TypeForm

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr.shape

(5,)

In [6]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(type(arr2))
print(arr2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [15]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#identity metric
print(np.identity(5))
np.eye(3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr3 = np.arange(1,12,2).reshape((2,3))

print("arr:\n" , arr)
print()

arr:
 [1 2 3 4 5]


In [ ]:
#attribute of numpy     
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(f"arr: {arr}")
print(f"arr shape: {arr.shape}")
print(f"arr no of dimension {arr.ndim}")
print(f"dataType: {arr.dtype}")
print(f"item size : {arr.itemsize}")

arr: [[1 2 3]
 [4 5 6]]
arr shape: (2, 3)
arr no of dimension 2
dataType: int64
item size : 8


In [7]:
##numpy vertorized operations
arr1 =np.array([1,2,3,5,6])
arr2 = np.array([10,20,30,40,50])
print(f"arr + arr1 : {arr1 +arr2}")
print(f"arr1 -arr2 : {arr1 - arr2}")
print(f"arr1 *arr2 : {arr1 * arr2}")
print(f"arr1 /arr2 : {arr1 / arr2}")



arr + arr1 : [11 22 33 45 56]
arr1 -arr2 : [ -9 -18 -27 -35 -44]
arr1 *arr2 : [ 10  40  90 200 300]
arr1 /arr2 : [0.1   0.1   0.1   0.125 0.12 ]


In [12]:

# Universial function  that applied to entire array

arr = np.array([4,9,16,25,36])
print(np.sqrt(arr))
#exponential 
print(np.exp(arr))
#sine
print(np.sin(arr))
print(np.log(arr))

[2. 3. 4. 5. 6.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10
 4.31123155e+15]
[-0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]
[1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]


In [23]:
#my universal function
#array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [1,2,3,4]])
print(f"array : {arr[0][3]}")
print(f"arr {arr[0][0]}")
print(f"arr : {arr[0:2,2:]}")

array : 4
arr 1
arr : [[3 4]
 [7 8]]


In [19]:
print(f"arr : {arr[1:]}")

print(f"arr : {arr[1:, 2:]}")


arr : [[5 6 7 8]
 [1 2 3 4]]
arr : [[7 8]
 [3 4]]


In [26]:
# modify
arr[0,0] = 100
print(f"arr : {arr}")

arr[1:] = 99
print(f"arr : {arr}")


arr : [[100   2   3   4]
 [ 99  99  99  99]
 [ 99  99  99  99]]
arr : [[100   2   3   4]
 [ 99  99  99  99]
 [ 99  99  99  99]]


In [28]:
## statistical concept normalization
# to have a mean of 0 and standard deviation of 1

from numpy import mean


data = np.array([1,2,3,4,5,6])
mean = np.mean(data)
std_dev= np.std(data)
print(mean , std_dev)

normalization= (data - mean) / std_dev
print("Normalization data :" , normalization)

3.5 1.707825127659933
Normalization data : [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [31]:
data = np.array([1,2,3,4,5,6, 7])
print(f"mean : {np.mean(data)}")
print(f"Median : {np.median(data)}")
print(f"standard deviation :{np.std(data)}")
print(f"variance: {np.var(data)}")

mean : 4.0
Median : 4.0
standard deviation :2.0
variance: 4.0


In [41]:
## Logical operation 
data = np.array([1,2,3,4,5,6,6,7,7,8])
data[(data>5) & (data<8)]


array([6, 6, 7, 7])