Numpy is a fundamental library for scientific computing in python. it provides support for arrays and matrics, along with a collection of mathematical functions to operate on these data structure, in this lession we will cover the basic of Numpy, focusing on arrays and vectorized operation.

In [ ]:
!pip install numpy


In [2]:
from typing_extensions import TypeForm

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr.shape

(5,)

In [6]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(type(arr2))
print(arr2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [15]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#identity metric
print(np.identity(5))
np.eye(3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr3 = np.arange(1,12,2).reshape((2,3))

print("arr:" , arr)
print("arr:" ,arr.shape )
print(f"arr: {arr.ndim}")
print(f"arr : {arr.size}")
print(f"arr {arr.dtype}")
print(f"item size {arr.itemsize}")

arr:
 [1 2 3 4 5]
